### ISSUE TITLE
Hoe te implementeren

### ISSUE THREAD

**Issue by ZonPV** [proditaki/OTGW-Domoticz-MQTT-Client#6]
Dag Dirk,
Fijn dat er er een plugin is voor het uitwisselen van data tussen OTGW en Domoticz. Ben benieuwd of dit meer gegevens gaat opleveren over mijn CV. 
Heb daarvoor een upgrade gedaan van de oude hardwareversie 0.9.9.3 naar de meest recente. Helaas nu (nog) wel wat minder data (modulatie-niveau bijvoorbeeld) uit de cv-ketel beschikbaar. Mogelijk is daar via MQTT wat meer uit te halen?

Ik draai ook Mosquito broker lokaal op de NAS en de MQTT Client Gateway with LAN interface in Domoticz

Maar het is me niet duidelijk hoe deze plugin te installeren in Domoticz Version: 2021.1 (build 13872) in een docker-omgeving op mijn Synology NAS. Zou je daar korte beschrijving over kunnen geven?

Met dank, Pieter

**Comment by antonlamers** [comment]
Hoi Pieter,

Je kunt ook de orgiele mqtt plugin installeren, welke ju nu hebt maar dam moet je geen otgw firmware 5 of nieuwer hebben.
Ik heb het op deze mannier gedaan wel docker op een raspberry pi:
cd volumes/domoticz/plugins/
sudo git clone https://github.com/proditaki/OTGW-Domoticz-MQTT-Client.git

*Restart domoticz

**Comment by ZonPV** [comment]
@antonlamers Dank voor aanvulling. Ik heb e.e.a. inmiddels werkend gekregen en werkinstructie aangeleverd via andere route. Dit issue kan gesloten worden. Sorry voor late reactie.
